export const productsData = [
  // ─── SNEAKERS ───────────────────────────────────────────────────────────────
  {
    name: "Air Jordan 1 Retro High OG",
    brand: "Jordan",
    category: "sneakers",
    subcategory: "basketball",
    price: "189.99",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    description:
      "The Air Jordan 1 Retro High OG is a classic basketball shoe that has stood the test of time. Featuring premium leather construction and the iconic Wings logo, it offers both style and performance.",
    colorway: "Black/White-Varsity Red",
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "12"],
    inStock: true,
    isNew: false,
    isFeatured: true,
    isSale: false,
    rating: "4.9",
    reviewCount: 2847,
  },
  {
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    category: "sneakers",
    subcategory: "lifestyle",
    price: "110.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    ],
    description:
      "The radiance lives on in the Nike Air Force 1 '07, the basketball original that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash.",
    colorway: "White/White",
    sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "12", "13"],
    inStock: true,
    isNew: false,
    isFeatured: true,
    isSale: false,
    rating: "4.8",
    reviewCount: 5432,
  },
  {
    name: "Adidas Yeezy Boost 350 V2",
    brand: "Adidas",
    category: "sneakers",
    subcategory: "lifestyle",
    price: "220.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80",
    ],
    description:
      "Yeezy Boost 350 V2 features a Primeknit upper, a full-length Boost midsole, and a translucent side stripe. A modern silhouette born from functional design.",
    colorway: "Zebra",
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11"],
    inStock: true,
    isNew: false,
    isFeatured: true,
    isSale: false,
    rating: "4.7",
    reviewCount: 3219,
  },
  {
    name: "Nike Dunk Low Retro",
    brand: "Nike",
    category: "sneakers",
    subcategory: "lifestyle",
    price: "110.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    description:
      "Created for the hardwood but taken to the streets, the '80s basketball icon returns with classic details and college-inspired colorways. The padded collar and foam midsole provide court-ready cushioning.",
    colorway: "Black/White",
    sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "12"],
    inStock: true,
    isNew: true,
    isFeatured: true,
    isSale: false,
    rating: "4.8",
    reviewCount: 1876,
  },
  {
    name: "New Balance 990v6",
    brand: "New Balance",
    category: "sneakers",
    subcategory: "running",
    price: "184.99",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
    ],
    description:
      "The New Balance 990v6 combines legendary comfort with premium materials. Made in the USA with domestic and imported parts, it features ENCAP midsole cushioning and a pigskin/mesh upper.",
    colorway: "Grey/White",
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "11.5", "12"],
    inStock: true,
    isNew: true,
    isFeatured: false,
    isSale: false,
    rating: "4.9",
    reviewCount: 987,
  },
  {
    name: "Nike Air Max 90",
    brand: "Nike",
    category: "sneakers",
    subcategory: "lifestyle",
    price: "130.00",
    originalPrice: "130.00",
    image: "https://images.unsplash.com/photo-1607522370275-f6fd21250e4d?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1607522370275-f6fd21250e4d?w=800&q=80",
    ],
    description:
      "Nothing as fly, nothing as comfortable, nothing as proven. The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle outsole, stitched overlays and classic TPU details.",
    colorway: "White/Black-Wolf Grey",
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "12"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: false,
    rating: "4.7",
    reviewCount: 2341,
  },
  {
    name: "Adidas Ultraboost 22",
    brand: "Adidas",
    category: "sneakers",
    subcategory: "running",
    price: "190.00",
    originalPrice: "190.00",
    image: "https://images.unsplash.com/photo-1556048219-bb6978360b84?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556048219-bb6978360b84?w=800&q=80",
    ],
    description:
      "Lace up in energy-returning comfort. These running shoes feature a Primeknit+ upper that hugs your foot like a second skin and a full-length BOOST midsole for incredible energy return.",
    colorway: "Core Black/Carbon",
    sizes: ["6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "12"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: true,
    rating: "4.6",
    reviewCount: 1543,
  },
  {
    name: "Converse Chuck Taylor All Star",
    brand: "Converse",
    category: "sneakers",
    subcategory: "lifestyle",
    price: "65.00",
    originalPrice: "65.00",
    image: "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=800&q=80",
    ],
    description:
      "The Chuck Taylor All Star is the world's most iconic sneaker. Original canvas upper. Medial eyelets enhance airflow. Original rubber outsole.",
    colorway: "Black/Black-White",
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "11", "12"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: false,
    rating: "4.5",
    reviewCount: 8923,
  },
  {
    name: "Nike Air Jordan 4 Retro",
    brand: "Jordan",
    category: "sneakers",
    subcategory: "basketball",
    price: "210.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1584735175315-9d5df23be7be?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1584735175315-9d5df23be7be?w=800&q=80",
    ],
    description:
      "The Air Jordan 4 Retro features a mesh upper with suede overlays, visible Air cushioning, and a plastic wing collar. A certified classic from the Michael Jordan era.",
    colorway: "Black/Cement Grey-Fire Red",
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11", "12"],
    inStock: true,
    isNew: true,
    isFeatured: true,
    isSale: false,
    rating: "4.9",
    reviewCount: 1234,
  },
  {
    name: "Vans Old Skool",
    brand: "Vans",
    category: "sneakers",
    subcategory: "skate",
    price: "70.00",
    originalPrice: "70.00",
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80",
    ],
    description:
      "The Old Skool, Vans' first skate shoe to feature the iconic side stripe, has a low-top lace-up style with a durable canvas and suede upper with padded tongue and lining.",
    colorway: "Black/White",
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "11", "12"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: false,
    rating: "4.6",
    reviewCount: 4567,
  },
  {
    name: "Nike Zoom Vomero 5",
    brand: "Nike",
    category: "sneakers",
    subcategory: "running",
    price: "160.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
    ],
    description:
      "The Nike Zoom Vomero 5 is a modern take on Y2K runner aesthetics. Built for performance but styled for the streets, it combines Zoom Air cushioning with a premium upper.",
    colorway: "Summit White/Black",
    sizes: ["7", "7.5", "8", "8.5", "9", "9.5", "10", "10.5", "11"],
    inStock: true,
    isNew: true,
    isFeatured: true,
    isSale: false,
    rating: "4.7",
    reviewCount: 654,
  },
  {
    name: "Adidas Stan Smith",
    brand: "Adidas",
    category: "sneakers",
    subcategory: "lifestyle",
    price: "100.00",
    originalPrice: "100.00",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80",
    ],
    description:
      "More than 50 years after their debut, the Stan Smith sneakers remain as fresh as ever. The clean, minimalist design of these shoes has made them a timeless classic.",
    colorway: "Cloud White/Green",
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "11", "12"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: true,
    rating: "4.6",
    reviewCount: 3456,
  },
  // ─── CLOTHING ────────────────────────────────────────────────────────────────
  {
    name: "Nike Tech Fleece Hoodie",
    brand: "Nike",
    category: "clothing",
    subcategory: "hoodies",
    price: "110.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80",
    ],
    description:
      "Nike Tech Fleece Hoodie delivers warmth without the bulk. The innovative material is designed to keep you comfortable whether you're training or just hanging out.",
    colorway: "Black",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    isNew: false,
    isFeatured: true,
    isSale: false,
    rating: "4.8",
    reviewCount: 2134,
  },
  {
    name: "Adidas Trefoil Hoodie",
    brand: "Adidas",
    category: "clothing",
    subcategory: "hoodies",
    price: "75.00",
    originalPrice: "75.00",
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=800&q=80",
    ],
    description:
      "A relaxed fit hoodie with the iconic Trefoil logo. Made with comfortable cotton-blend fabric, perfect for everyday wear.",
    colorway: "Black",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: false,
    rating: "4.5",
    reviewCount: 876,
  },
  {
    name: "Off-White Diagonal Stripe Tee",
    brand: "Off-White",
    category: "clothing",
    subcategory: "t-shirts",
    price: "280.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80",
    ],
    description:
      "Off-White's iconic diagonal stripe graphic tee in heavyweight cotton. A streetwear staple that defines contemporary fashion.",
    colorway: "White/Black",
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: false,
    rating: "4.6",
    reviewCount: 432,
  },
  {
    name: "Champion Reverse Weave Sweatshirt",
    brand: "Champion",
    category: "clothing",
    subcategory: "sweatshirts",
    price: "65.00",
    originalPrice: "65.00",
    image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&q=80",
    ],
    description:
      "Champion's Reverse Weave fabric reduces shrinkage in the length. The ribbed side inserts give the appearance of a slimmer fit while allowing freedom of movement.",
    colorway: "Oxford Grey",
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: true,
    rating: "4.4",
    reviewCount: 1234,
  },
  {
    name: "Stone Island Cargo Pants",
    brand: "Stone Island",
    category: "clothing",
    subcategory: "pants",
    price: "395.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80",
    ],
    description:
      "Stone Island cargo pants in garment-dyed cotton canvas. Features the iconic compass badge on the upper thigh. Elastic drawstring waist with button closure.",
    colorway: "Black",
    sizes: ["28", "30", "32", "34", "36", "38"],
    inStock: true,
    isNew: true,
    isFeatured: true,
    isSale: false,
    rating: "4.8",
    reviewCount: 234,
  },
  {
    name: "Jordan Flight MVP Shorts",
    brand: "Jordan",
    category: "clothing",
    subcategory: "shorts",
    price: "60.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80",
    ],
    description:
      "Jordan Flight MVP Shorts feature sweat-wicking fabric and a smooth interior for unrestricted movement. Side pockets keep your essentials secure.",
    colorway: "Black/White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: false,
    rating: "4.5",
    reviewCount: 567,
  },
  {
    name: "Supreme Box Logo Crewneck",
    brand: "Supreme",
    category: "clothing",
    subcategory: "sweatshirts",
    price: "168.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&q=80",
    ],
    description:
      "Supreme's iconic Box Logo crewneck sweatshirt. Made from heavyweight fleece with a ribbed collar, cuffs and hem. A streetwear essential.",
    colorway: "Black",
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: false,
    isNew: false,
    isFeatured: true,
    isSale: false,
    rating: "4.9",
    reviewCount: 789,
  },
  {
    name: "Carhartt WIP Active Jacket",
    brand: "Carhartt WIP",
    category: "clothing",
    subcategory: "jackets",
    price: "170.00",
    originalPrice: "170.00",
    image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&q=80",
    ],
    description:
      "The Carhartt WIP Active Jacket is a workwear-inspired piece with a relaxed fit. Features multiple pockets, a stand collar and snap button closure.",
    colorway: "Black",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    isNew: false,
    isFeatured: true,
    isSale: true,
    rating: "4.7",
    reviewCount: 432,
  },
  {
    name: "Nike Essential Joggers",
    brand: "Nike",
    category: "clothing",
    subcategory: "pants",
    price: "55.00",
    originalPrice: "55.00",
    image: "https://images.unsplash.com/photo-1580906853135-3534e5b5cd7e?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1580906853135-3534e5b5cd7e?w=800&q=80",
    ],
    description:
      "Nike Essential Joggers feature soft, sweat-wicking fabric for all-day comfort. The tapered fit and elastic waistband provide a modern look and secure feel.",
    colorway: "Black",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    isNew: false,
    isFeatured: false,
    isSale: false,
    rating: "4.5",
    reviewCount: 1876,
  },
  {
    name: "Stüssy 8 Ball Tee",
    brand: "Stüssy",
    category: "clothing",
    subcategory: "t-shirts",
    price: "42.00",
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80",
    ],
    description:
      "The Stüssy 8 Ball Tee features the brand's iconic 8 Ball graphic on the front and back. Made from 100% cotton for everyday comfort.",
    colorway: "White",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    isNew: true,
    isFeatured: false,
    isSale: false,
    rating: "4.6",
    reviewCount: 654,
  },
  {
    name: "The North Face Nuptse Jacket",
    brand: "The North Face",
    category: "clothing",
    subcategory: "jackets",
    price: "280.00",
    originalPrice: "280.00",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
    ],
    description:
      "The Nuptse Jacket is a legendary piece of outerwear. Filled with 700-fill-power recycled down and featuring a water-resistant shell, it's built for serious cold.",
    colorway: "TNF Black",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
    inStock: true,
    isNew: false,
    isFeatured: true,
    isSale: false,
    rating: "4.9",
    reviewCount: 2198,
  },
];
